CREATE SEQUENCE IF NOT EXISTS project_holiday_seq START WITH 770000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS projectholiday (
    project_holiday_id BIGINT PRIMARY KEY DEFAULT nextval('project_holiday_seq'),
    project_id BIGINT,
    industry_id BIGINT,
    holiday_id BIGINT,
    city_id BIGINT,
    -- Added this column to match your Spring Boot entity
    created_by VARCHAR(255),
    create_date_time TIMESTAMP,
    updated_by VARCHAR(255),
    update_date_time TIMESTAMP,
    status_id BIGINT
);

CREATE TABLE IF NOT EXISTS holiday (
    holiday_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_id BIGINT,
    country_id BIGINT,
    year_id BIGINT,
    holiday_name VARCHAR(255),
    day VARCHAR(255),
    comment VARCHAR(255),
    created_by VARCHAR(255),
    create_date_time TIMESTAMP,
    updated_by VARCHAR(255),
    update_date_time TIMESTAMP
    );

 CREATE TABLE IF NOT EXISTS Approval (
     approval_status_Id   BIGINT       NOT NULL PRIMARY KEY,
     approval_status_name VARCHAR(50)  NOT NULL UNIQUE,
     approval_status_desc VARCHAR(255) NOT NULL,
     created_by           VARCHAR(100) NOT NULL,
     create_date_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_by           VARCHAR(100) NOT NULL,
     update_date_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
 );

INSERT INTO Approval (
    approval_status_id,
    approval_status_name,
    approval_status_desc,
    created_by,
    create_date_time,
    updated_by,
    update_date_time
)
VALUES
(
    720,
    'Saved',
    'Saved but not sent for approval',
    'Rajeev',
    '2025-09-25 00:00:00',
    'Rajeev',
    '2025-09-25 00:00:00'
),
(
    721,
    'PendingApproval',
    'Sent for manager approval',
    'Rajeev',
    '2025-09-25 00:00:00',
    'Rajeev',
    '2025-09-25 00:00:00'
),
(
    722,
    'Rejected',
    'Request sent back by manager',
    'Rajeev',
    '2025-09-25 00:00:00',
    'Rajeev',
    '2025-09-25 00:00:00'
),
(
    723,
    'Approved',
    'Request approved by manager',
    'Rajeev',
    '2025-09-25 00:00:00',
    'Rajeev',
    '2025-09-25 00:00:00'
),
(
    724,
    'Default',
    'Only for select cases',
    'Rajeev',
    '2025-09-25 00:00:00',
    'Rajeev',
    '2025-09-25 00:00:00'
)
ON CONFLICT (approval_status_id) DO NOTHING;
-- Create Sequence
CREATE SEQUENCE IF NOT EXISTS public.project_working_days_seq
START WITH 88001
INCREMENT BY 1
MINVALUE 88001;

-- Create Table
CREATE TABLE IF NOT EXISTS public."projectworkingdays"
(
    project_working_day_id BIGINT PRIMARY KEY
        DEFAULT nextval('public.project_working_days_seq'),

    project_id BIGINT NOT NULL,

    day_id BIGINT NOT NULL,

    working_flag CHAR(1) NOT NULL,

    work_start_time TIME,

    work_end_time TIME,

    created_by VARCHAR(100),

    create_date_time TIMESTAMP,

    updated_by VARCHAR(100),

    update_date_time TIMESTAMP




);

-- Attach sequence ownership AFTER table creation
ALTER SEQUENCE public.project_working_days_seq
OWNED BY public."ProjectWorkingDays".project_working_day_id;

CREATE TABLE IF NOT EXISTS public.project_details (
    project_details_id      BIGINT PRIMARY KEY,

    industry_id             BIGINT,

    project_office_location VARCHAR(255),

    project_name            VARCHAR(255),

    project_contract_no     VARCHAR(255),

    project_date            DATE,

    project_address1        VARCHAR(255),

    project_address2        VARCHAR(255),

    project_city_id         BIGINT,

    project_state_id        BIGINT,

    project_city_pin_id     BIGINT,

    project_phone1          VARCHAR(50),

    project_phone2          VARCHAR(50),

    created_by              VARCHAR(255),

    create_date_time        TIMESTAMP,

    updated_by              VARCHAR(255),

    update_date_time        TIMESTAMP
);
CREATE TABLE IF NOT EXISTS public.project_task (
    task_id BIGSERIAL PRIMARY KEY,
    project_id BIGINT,
    mpp_task_id BIGINT,
    task_name VARCHAR(500),
    duration VARCHAR(100),
    start_date TIMESTAMP,
    finish_date TIMESTAMP,
    predecessors VARCHAR(200),
    resource_names VARCHAR(500),
    outline_level INTEGER,
    parent_task_id BIGINT
);